### ISSUE TITLE
Error: com.appsflyer.sdk.network after React Native upgrade

### ISSUE THREAD

**Issue by pabloearg** [AppsFlyerSDK/appsflyer-react-native-plugin#350] opened 2021-12-13 13:44 UTC
Hi Team, 

Production version -> "react-native-appsflyer": "6.2.42"
SO: iOS 
 
After our latest release, in which we updated the react native version of the app from 0.63.4 to 0.65.1. We are getting a lot of network errors (com.appsflyer.sdk.network) on Sentry, that are not even being grouped.

![image](https://user-images.githubusercontent.com/29818262/145822592-f0ffacbc-f6c3-452b-ad8b-7b696c0156dc.png)

![image](https://user-images.githubusercontent.com/29818262/145822681-a7796902-8118-4fac-bd1a-675248aff17a.png)

Is there a way to fix this?

**Comment by DimGun** [comment] 2021-12-31 10:09
Have the same issue, also caught by Sentry. Sent requested information to the support@appsflyer.com.
The questions are: What does this exception mean? Is it just that event could not be sent right now and it will be sent on the next occasion? Should we care?

**Comment by af-fess** [comment] 2022-01-01 20:53
Possible duplicate of https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/329

**Closed by af-fess** 2022-01-01 20:53 UTC
Labels: support

**Comment by roryf** [comment] 2022-05-24 18:15
Experiencing the same issue, after installing appsflyer
```
"react-native": "0.66.1",
    "react-native-appsflyer": "^6.5.21",
```

I don't think this is a duplicate of #329 which is asking what the cause of the error is, I think the issue here is the noise it creates in Sentry. Yes we can ignore it, but should the library be causing exceptions for transient network errors?

**Comment by LydGol90** [comment] 2022-06-21 15:07
Hi. We have also been battling with this issue, however I realised that for us it was due to our segment integration set up pointing to an apple app id for an app that no longer existed. (I had created it purely for debug testing). I have noticed that it can take some time after setting up a new app in appsflyer before it becomes "available" to the SDK and so was also seeing it in these cases. I've not confirmed but it may also happen if integration is turned off in Segment. Just posting this here in case this helps anyone else.

**Comment by arthurgeron-work** [comment] 2023-04-03 00:41
This same issue started happening to my project after I upgraded it to RN 0.71

**Comment by OHHAKO** [comment] 2023-04-24 08:05
same issue. 

```
"react-native": "0.69.4",
react-native-appsflyer": "^6.9.2",
```

**Comment by renanbronchart** [comment] 2023-06-01 22:09
The same, no fix on this issue, can we reopened this issue @af-fess ?

**Comment by amit-kremer93** [comment] 2023-06-05 06:45
@renanbronchart this issue happens randomly on AppsFlyer calls or on a specific calls? (logEvent, start, etc.) and do you know if it happens more on a specific device?

**Comment by bufgix** [comment] 2023-06-05 10:49
> @renanbronchart this issue happens randomly on AppsFlyer calls or on a specific calls? (logEvent, start, etc.) and do you know if it happens more on a specific device?

im getting same error when logEvent calls. My app running on IPhone 7 and IPhone 14 plus.


```tsx
  AppsflyerModule.logEvent(ANALYTICS_EVENTS.appsflyer.firstOpen, {}).catch(
    e => {
      console.log(e);
    },
  );
```

```bash
[Error: com.appsflyer.sdk.network]
```

**Comment by renanbronchart** [comment] 2023-06-07 09:13
> @renanbronchart this issue happens randomly on AppsFlyer calls or on a specific calls? (logEvent, start, etc.) and do you know if it happens more on a specific device?

OS: Only iOS
VersionOS : From 15 to 16
React-native version : Error appear after upgrading to 0.71

Here the public link of my sentry error:
https://toasty-hr.sentry.io/share/issue/9a24482a2f0042f2b1eefb7515a723c8/

<img width="325" alt="Capture d’écran 2023-06-07 à 11 12 23" src="https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/assets/16922579/6831fc76-42b5-46e2-9016-36d171fd44a6">

**Comment by dannyhw** [comment] 2023-06-08 13:25
also getting this as soon as we include the apps flyer plugin 

heres a patch I used to stop the warnings but not sure if theres some underlying problem

```
diff --git a/src/methods/track.ts b/src/methods/track.ts
index 2dcb88d63bf1626800eadcf58c3e6c1dbd2e4b83..8ca89e561b097613081168916f8c914dc88ac5f2 100644
--- a/src/methods/track.ts
+++ b/src/methods/track.ts
@@ -1,13 +1,13 @@
-import appsFlyer from 'react-native-appsflyer';
-import { isString, TrackEventType } from '@segment/analytics-react-native';
+import appsFlyer from "react-native-appsflyer";
+import { isString, TrackEventType } from "@segment/analytics-react-native";
 
 type Properties = { [key: string]: unknown };
 
 export default async (event: TrackEventType) => {
   const properties = event.properties || {};
 
-  const revenue = extractRevenue('revenue', properties);
-  const currency = extractCurrency('currency', properties, 'USD');
+  const revenue = extractRevenue("revenue", properties);
+  const currency = extractCurrency("currency", properties, "USD");
 
   if (
     revenue !== undefined &&
@@ -16,19 +16,23 @@ export default async (event: TrackEventType) => {
     currency !== null
   ) {
     const otherProperties = Object.entries(properties)
-      .filter(([key]) => key !== 'revenue' && key !== 'currency')
+      .filter(([key]) => key !== "revenue" && key !== "currency")
       .reduce((acc: Properties, [key, val]) => {
         acc[key] = val;
         return acc;
       }, {});
 
-    await appsFlyer.logEvent(event.event, {
-      ...otherProperties,
-      af_revenue: revenue,
-      af_currency: currency,
-    });
+    await appsFlyer
+      .logEvent(event.event, {
+        ...otherProperties,
+        af_revenue: revenue,
+        af_currency: currency,
+      })
+      .catch((e) => console.log("segment appsflyer plugin error", e));
   } else {
-    await appsFlyer.logEvent(event.event, properties);
+    await appsFlyer
+      .logEvent(event.event, properties)
+      .catch((e) => console.log("segment appsflyer plugin error", e));
   }
 };
 
@@ -39,9 +43,9 @@ const extractRevenue = (key: string, properties: Properties): number | null => {
   }
 
   switch (typeof value) {
-    case 'number':
+    case "number":
       return value;
-    case 'string':
+    case "string":
       return parseFloat(value);
     default:
       return null;
@@ -54,7 +58,7 @@ const extractCurrency = (
   defaultCurrency: string
 ): string => {
   const value = properties[key];
-  if (isString(value)) {
+  if (typeof value === "string") {
     return value;
   }
   return defaultCurrency;
```

**Comment by ahtokca** [comment] 2023-09-21 21:08
same here

react-native 0.72.4
react-native-appsflyee ^6.12.2

is there a solution? why the ticket is closed?

**Comment by mohanramCypherD** [comment] 2024-01-18 10:32
Hey team, facing the same issue. There is no proposed solution for this issue provided in this thread. Any updates on fixing this ?

**Comment by pooja-turnip** [comment] 2024-06-04 17:24
@ge-af : We have been facing the same issue. Native apps both on android and ios. We have raised the issue with appsflyer support team but there is no resolution. Was a solution found for this issue?

**Comment by giaset** [comment] 2024-08-01 03:13
Same issue on our end, makes our logs quite noisy

**Comment by brascene** [comment] 2024-09-30 09:20
Why is this closed, if we still experience this?

**Comment by envisean** [comment] 2025-03-15 04:59
We're experiencing this on our app that was working up until September 2024. Looks like data shut off and we've been seeing this issue in react-native now.

We are using both segment and incorporating this as a plugin and followed the Segment docs. The initial integration was fine, but now it's struggling.

Has anyone had success with this after they started using Hermes?
