### ISSUE TITLE
Undefined symbols for architecture i386:   "_OBJC_CLASS_$_AppsFlyerAttribution", referenced from:

### ISSUE THREAD

**Issue by s-karthik543** [AppsFlyerSDK/appsflyer-react-native-plugin#268] opened 2021-03-23 09:38 UTC
Getting the below error while compiling ios build
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_AppsFlyerAttribution", referenced from:
      objc-class-ref in libRNAppsFlyer.a(RNAppsFlyer.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

react-native : 0.59.5
Xcode: 11.3.1
react-native-appsflyer: 6.2.30

**Comment by af-fess** [comment] 2021-03-23 10:49
Possible duplicate of https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/104

**Comment by s-karthik543** [comment] 2021-03-23 11:04
Working fine with react-native-appsflyer version 5.0.0. After updating appsflyer version getting the above error. In the AppsFlyerLib.framework, files related to AppsFlyerAttribution are missing

**Comment by af-fess** [comment] 2021-03-23 11:28
in 6.+ we changed the public API. https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin#--breaking-changes

**Comment by s-karthik543** [comment] 2021-03-24 03:06
@af-fess I have committed the sample code here. I'm still not able to compile it. Please hep to fix this

**Comment by amit-kremer93** [comment] 2021-03-24 07:09
@s-karthik543 `AppsFlyerAttribution` is not part of `AppsFlyerLib.framework`. please download the plugin from github or npm and install it again.

**Comment by s-karthik543** [comment] 2021-03-24 07:35
@amit-kremer93 I have downloaded the plugin from github only. You can check the sample code which i shared above. Please help to fix this issue

**Comment by s-karthik543** [comment] 2021-03-26 08:54
This issue is fixed

**Closed** 2021-03-29 05:31 UTC

**Comment by RazaShehryar** [comment] 2021-06-21 15:45
@s-karthik543 how did you fix this issue? I am still getting this issue

**Comment by jpmasud** [comment] 2021-10-30 06:39
In XCode, have to go to Project -> General -> Frameworks, Libraries & Embedded Content -> Add the AppsFlyerLib.xcframework

**Comment by leitdeux** [comment] 2022-03-03 03:43
The following is advice for anyone *manually* integrating the **RNAppsFlyer.xcodeproj** into your workspace (instead of using Cocoapods nor `react-native link`):

After manually dragging the **RNAppsFLyer.xcodeproj** file into my app's workspace, I could not compile due to "undefined symbols" errors from the compiler. It turns out that not all of the files found in the repository `react-native-appsflyer/ios` directory where the **RNAppsFlyer.xcodeproj** file resides are actually included in `RNAppsFlyer`; i.e. you will only find the files `RNAppsFlyer.h`, `RNAppsFlyer.m` and `AppsFlyerLib.h` initially after dragging the project into your app's workspace.

To get my app compiling again I needed to manually drag in the following files into the `RNAppsFlyer` library found in my app's Xcode workspace project:

```
AppsFlyerCrossPromotionHelper.h
AppsFlyerLinkGenerator.h
AppsFlyerShareInviteHelper.h
AppsFlyerLinkGenerator.h
AppsFlyerShareInviteHelper.h
AppsFlyerAttribution.h
AppsFlyerAttribution.m
AppsFlyerCrossPromotionHelper.h
AppsFlyerDeepLink.h
AppsFlyerDeepLinkObserver.h
AppsFlyerDeepLinkResult.h
```

Once I dragged those files in, the "undefined symbols" errors ceased and the project built successfully.
