### ISSUE TITLE
IOS error 7 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by skompaniets** [AppsFlyerSDK/appsflyer-react-native-plugin#476] opened 2023-06-28 09:59 UTC
# Report

## Plugin Version

ℹ Please replace these two lines with the plugin version.
"react-native-appsflyer": "^6.10.3"

## On what Platform are you having the issue?

ℹ Please replace these two lines with the SDK version.
IOS

## What did you do?

ℹ Please replace these two lines with what you did.  
rm -rf ~/Library/Developer/Xcode/iOS DeviceSupport
rm -rf ~/Library/Caches/com.apple.dt.Xcode
rm -rf ~/Library/Developer/CoreSimulator/Caches
rm -rf ~/Library/Developer/Xcode/DerivedData
rm -fr ios/Pods
rm -fr ios/Podfile.lock
cd ios && pod repo remove trunk&&pod install --repo-update

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
app build success

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
7 duplicate symbols for architecture x86_64
<img width="268" alt="Screenshot 2023-06-28 at 12 59 27" src="https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/assets/122784167/13ad1e6b-e346-4212-a4de-56dd06123383">

## Please provide any other relevant information.

ℹ Please replace these two lines with more information.
using react-native: "0.70.6", upgraded rn to "0.71.7" - the same

**Comment by amit-kremer93** [comment] 2023-07-13 07:39
Duplicate of https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/459?

**Closed** 2023-07-31 14:01 UTC
Labels: waiting for customer response, Platform: iOS
