### ISSUE TITLE
Direct deep linking not working when app is full closed

### ISSUE THREAD

**Issue by JHPG** [AppsFlyerSDK/appsflyer-react-native-plugin#214] opened 2020-11-17 16:22 UTC
# Report

## Plugin Version

`6.1.0`

## On what Platform are you having the issue?

Android and iOS.

## What did you do?

I added the direct deep linking configuration as the documentation shows. Once configured, opened a valid deep link that redirects to the app.

## What did you expect to happen?

Open the correct action every time a direct deep link is opened.

## What happened instead?

Works well when the app is in background, but if it is full closed, the `onAppOpenAttribution` callback is not called when the app opens.

## Please provide any other relevant information.

- I've already set the `onNewIntent` in MainActivity
- `onAppOpenAttribution` method was made prior to the `initSdk`

**Comment by amit-kremer93** [comment] 2020-11-18 07:20
Hi @JHPG and thank you for opening this issue.
Be sure that you completed the instructions [here](https://support.appsflyer.com/hc/en-us/articles/208874366) and [here](https://support.appsflyer.com/hc/en-us/articles/207033836).
you can try to log a test message in `AppsFlyerConversionListener` in the native side of the plugin, inside `onAppOpenAttribution` to see if you get response from the sdk.

**Comment by JHPG** [comment] 2020-11-19 20:30
I read the two links you sent about that, but it is the same guides we’ve followed previously. Nevertheless I revised every item to make sure I didn’t miss anything.

We've already tried to log messages on the RN side and this is how we identified when happens this issue.

From what I realized, the app is not calling the “onAppOpenAttribution” when it opens, only when it resumes the execution. This could be the reason why deep links only work when the app is open in the background.

**Comment by amit-kremer93** [comment] 2020-12-20 09:41
@JHPG Direct Deep Link should work fine for android, be sure you read and implement every step in the DOCS. you can read more [here](https://dev.appsflyer.com/docs/deep-linking-existing-app-users-to-specific-content) in order to understand the flow better or contact our support team: support@appsflyer.com.
About iOS, there is another [issue](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/223) that was opened and I gave a workaround for that. so I close this issue and please follow the other one

**Closed by amit-kremer93** 2020-12-20 09:41 UTC
Labels: checking

**Comment by balandinS** [comment] 2021-02-01 09:50
greeting frieands.

I have a same issue 

I read and implement every step in the DOCS
@JHPG 
if success to solved the problem ?

**Comment by iway1** [comment] 2024-08-17 17:37
@amit-kremer93 why don't you all fix the actual problem instead of providing a work around in a random GitHub issue?

**Comment by zjkuang** [comment] 2025-07-10 05:05
I had the same issue on Android, and weird enough, it happens only when
(1) It is a Play Store release build. (We have internal distribution on Firebase App Distribution, also release build, but  it works well in such build. I don't know what the difference is there.)
(2) A cold start, which means the app has been killed when the AppsFlyer OneLink is tapped.

It is a race condition, since it occasionally worked, very very rare though, perhaps less than 1 out of 20.

The issue is that AppsFlyer.onAppOpenAttribution is not triggered in the case of cold start. And it is only in AppsFlyer.onAppOpenAttribution we have the chance to read the deep_link_value.

I did some experiments on the native side and found that the subscriber in MainActivity, AppsFlyerLib.getInstance().subscribeForDeepLink, could be steadily triggered in both cold and warm start, and the deep_link_value is available. So my solution is

(1) In MainApplication's onCreate,
```
AppsFlyerLib.getInstance().init(gbis.gbandroid.BuildConfig.APPSFLYER_DEV_KEY, appsFlyerConversionListener, this)
```
(2) In MainActivity's onCreate,
```
AppsFlyerLib.getInstance().subscribeForDeepLink { deepLink ->
  // save the `deepLink.deepLink.deepLinkValue`
  // sendEvent("notifyJavaScriptOfAppsFlyerDeepLink") to React Native
}
// As per the official doc, `subscribeForDeepLink` must be before `start`
AppsFlyerLib.getInstance().start(this, gbis.gbandroid.BuildConfig.APPSFLYER_DEV_KEY)
```
(3) On the React Native side
(3.1) When the app is started or turned active, consume the deepLinkValue saved by the subscriber in MainActivity
(3.2) Also listen for the event "notifyJavaScriptOfAppsFlyerDeepLink" and consume the deepLinkValue saved by the subscriber in MainActivity

And it worked perfectly.
