### ISSUE TITLE
Getting "JSON deserialization failed" on "onInstallConversionData"

### ISSUE THREAD

**Issue by gelobelo-espiritu** [AppsFlyerSDK/appsflyer-react-native-plugin#167] opened 2020-07-25 00:53 UTC
Was trying to implement "onInstallConversionData" but getting this error everytime
{"status":"failure","type":"onInstallConversionFailure","data":"JSON deserialization failed"}

# Report

## Plugin Version

react native appsflyer  - 5.4.1
react native  - 0.62.1

## On what Platform are you having the issue?
iOS 

## What did you do?

I did use autolinking feature of react native appsflyer

## What did you expect to happen?
"onInstallConversionData" would work fine as expected

## What happened instead?

Getting {"status":"failure","type":"onInstallConversionFailure","data":"JSON deserialization failed"} everytime

**Comment by dmitriiivashko** [comment] 2020-07-27 14:38
Having the same issue +1

**Comment by af-vs** [comment] 2020-07-28 07:11
Hi @gelobelo-espiritu and @dmitriiivashko!

We are not able to reproduce the issue.

Can you please enable AppsFlyer debug logs, reproduce the issue, and send generated iOS logs with `AppsFlyer` prefix over to vitaly.sokolov@appsflyer.com? Please don't post logs here to avoid compromising your app ID/dev Key. If necessary, we will repost them for visibility after hiding any possibly sensitive information). In the email, please add a link to this issue as a reference

In addition, if you can share a Sample App project that would be even better so that we can run and debug the issue, but lost should be fine to start with.

We will check this and post here our findings. Thank you!

**Comment by gelobelo-espiritu** [comment] 2020-07-29 13:52
Hi @af-vs  already emailed you with the logs in the email you provided. Hoping this would help in solving the issue.

**Comment by af-vs** [comment] 2020-07-30 09:46
Thanks to @gelobelo-espiritu we were able to reproduce the issue and figured that it is coming from the iOS native SDK and not React Native plugin. We have notified native SDK developers of the issue and expect it to be fixed in one of the future releases.

The issue is about the message in the Failure callback. When getting a 403 error from the server, instead of generic `JSON deserialization failed` error which is not clear we will work on returning more meaningful error messages containing error code.

As for the specific error reason, I suggest contacting the AppsFlyer Support team at support@appsflyer.com to check why GCD fails on the first place

**Comment by safciplak** [comment] 2020-08-09 13:35
i didnt get install data still, i tried raect native plugin
and second i tried with native.

**Comment by af-vs** [comment] 2020-08-09 15:22
@safciplak Unless you get exact same error message as described in my previous comment, please open a separate issue and provide as much information as you can, including debug logs.

If you get the same JSON deserialization error, please contact Support as it is only possible to get such in case the server responded with no proper JSON body and should be investigated by our Support team. 

Thank you!

**Comment by af-vs** [comment] 2020-09-02 10:50
Will be fixed in 6.0.2

**Comment by gelobelo-espiritu** [comment] 2020-09-02 13:13
Great news will check out :)

**Comment by af-vs** [comment] 2020-09-03 14:29
We have released 6.0.20, please try to use the new version, the issue should be resolved. Thanks!

**Comment by agusvazquez** [comment] 2020-09-03 14:39
Hello @af-vs I updated to 6.0.20 and I am experiencing the same issue on Android.

`{"status":"failure","type":"onInstallConversionFailure","data":"Error connection to server: 400"}", name: "AFParseJSONException"}`

```
onInstallConversionDataCanceller = appsFlyer.onInstallConversionData(
    (res) => {
      console.log(res);
      if (JSON.parse(res.data.is_first_launch) == true) {
        if (res.data.af_status === 'Non-organic') {
          var media_source = res.data.media_source;
          var campaign = res.data.campaign;
          /*alert(
            'This is first launch and a Non-Organic install. Media source: ' +
              media_source +
              ' Campaign: ' +
              campaign,
          );*/
        } else if (res.data.af_status === 'Organic') {
          //alert('This is first launch and a Organic Install');
        }
      } else {
        //alert('This is not first launch');
      }
    },
  );
```

**Comment by af-vs** [comment] 2020-09-03 14:47
Hi @agusvazquez!

What you get is a legit data from the SDK perspective. The issue that we fixed only affects iOS and is about returning generic error without error code. 

In your case you can see that server responded with 400. It may be caused by multiple reasons, most likely some integration mistakes. To understand the reasons please contact our support team.

Thank you!

**Comment by agusvazquez** [comment] 2020-09-03 14:49
Got it!

Thanks!

**Comment by vrazn** [comment] 2020-09-11 02:57
Currently experiencing the same thing in production which leads to an instant crash on Android (iOS seems to work just fine):
```
{status: "failure", type: "onInstallConversionFailure", data: "Error connection to server: 403"}
```

Started to happen recently, not sure what might be the cause.
I just checked the devKey and the implementation of onInstallConversionData, everything is according to the docs.

**Comment by af-vs** [comment] 2020-09-14 07:29
Hi @vrazn!

Same as above, you may need to reach out to Support to understand why you are getting a 403 error code (usually it is a devKey mismatch but might be something else I am not aware of).

As for the crash, I assume you may need to look into your error handling logic in case of the onInstallConversionFailure callback.

Again, this issue was opened due to the error message being not clear and not returning the error code. Since the original issue was solved by now I will close it to avoid any further confusion. Thanks!

**Closed by af-vs** 2020-09-14 07:29 UTC
Labels: native sdk bug, on hold, support
